Properly configure LOGGING Django variable in the settings to output …
aphp/Cohort360-Back-end pull request #17
Opened 2022-08-18 12:08 UTC by Dubrzr

This PR proposes the following changes:

* Some README updates
* renamed files example_* to example.* and modified two relative imports
* Add a LOGGING Django variable in the settings.py file to get better logging outputs (with stacktrace even in production and send emails to admins when a bug happens).

2022-08-18 12:33 UTC, alexandreMartinEcl requested changes

2022-08-18 12:33 UTC, alexandreMartinEcl commented on admin_cohort/models.py
> +def get_or_create_user_with_info(user_info: conf_auth.UserInfo) -> User:
A vrai dire, le type "UserInfo" ne provient pas de conf_auth, mais de example_conf_auth

Il sert à définir le type de réponse que doit renvoyer la fonction du fichier de conf_, car ce type demande des fields particuliers exploités dans le code source

2022-08-18 12:57 UTC, Dubrzr commented on admin_cohort/models.py
> +def get_or_create_user_with_info(user_info: conf_auth.UserInfo) -> User:
Hmm tu veux dire que ces types ne peuvent pas être définis dans la config ? Est-ce qu'on les sortirait pas de example_conf* du coup ?

2022-08-18 14:06 UTC, Dubrzr commented
J'ai fait un commit où je propose une solution pour le problème des types en exportant ce genre de classes vers un fichier types.py, je peux faire différemment.
Merci pour ta review @alexandreMartinEcl

2022-08-19 12:47 UTC, alexandreMartinEcl approved these changes

2022-08-19 12:49 UTC, alexandreMartinEcl commented
Added logging and redefined example.conf_ files' utility in admin_cohort and exports folders.

2022-08-19 12:50 UTC, merged